### ISSUE TITLE
WTF happened here?

### ISSUE THREAD

**Issue by ThiefMaster** [keycloak-client/keycloak-client#1]
New repo, no commit history, new github account, etc...

> Due to some legal issues we had to delete the original repository and releases
> We are extremely sorry for the inconveniences caused

This is VERY vague, and one would first think something fishy is going on here... but i did not find malicious code in the PyPI package.

But I think I'm not the only one who'd like to know what exactly those legal reasons are that required you to DELETE packages and commit history, instead of just renaming the repo and removing whatever may be problematic in a git commit (or, worst case, by rewriting history).

**Comment by ybinnenwegin2ip** [comment]
+1

@akhilputhiry / @larsw (?)

Can you comment on what has happened here?

**Comment by cute-as-ducks** [comment]
Hi Everyone

According to @akhilputhiry job contract, He is not allowed to do any open source contribution.
He had to delete the repository and hand it over to me, after getting legal notice from his company.
I will be maintaining the repository going forward

Thanks

**Comment by akhilputhiry** [comment]
Hey Guys, Sorry for doing this. I had no other option. Apologies

**Comment by ybinnenwegin2ip** [comment]
> Hi Everyone
> 
> According to @akhilputhiry job contract, He is not allowed to do any open source contribution. He had to delete the repository and hand it over to me, after getting legal notice from his company. I will be maintaining the repository going forward
> 
> Thanks

Thanks for your reply, I have to say I'm still not entirely convinced this is the way this project should move forward. The new github account with a random name is pretty fishy like @ThiefMaster already mentioned.

To give the project a bit more credibility back, how about pushing the old repository back so we at least have a commit history? If this is problematic because the name of the previous developer would still be there, perhaps the name of the author can be rewritten.

This obviously doesn't solve all problems but will be a step in the right direction.

I have the old project still forked here: https://github.com/ybinnenwegin2ip/keycloak-client which has the commit history up to the async clients being added. I may have a slightly newer version on my computer at home, would need to check.

> Hey Guys, Sorry for doing this. I had no other option. Apologies

Thanks for your reply, good luck at your new job and thanks for your work on keycloak-client.

**Comment by cute-as-ducks** [comment]
Make sense @ybinnenwegin2ip Let me push your clone. And I shall add the latest on top of it.

**Comment by ThiefMaster** [comment]
> He is not allowed to do any open source contribution.
> He had to delete the repository and hand it over to me, after getting legal notice from his company.

Something I don't understand:

- Is this his current company? If yes, wouldn't it make more sense to lawyer up (or find a company that doesn't suck as much)? Unless he used work resources, it's most likely not legal to prohibit him from doing Open Source work in his free time at home. And if he did use work resources, that'd probably give the company some copyright to the code, but any halfway decent company should realize that having it taken down is in nobody's interest.
- Is this a new company? If yes, there's no chance they can force him to retroactively remove Open Source contributions... even though they could of course decide to not hire him, but then the question should be "do I want to work for that company at all".

Anyway, I don't know his living/working conditions but it seems like everyone who works in this field should **strongly** oppose any employment contract clauses that would prohibit them from doing Open Source contributions in their free time.

In fact, I think his company would deserve public shaming for this, but of course I can fully understand that he won't name it if he's still working there...
